version: '2.1'
services:
    mysql-account:
       build: mysql
       ports: 
        - "3340:3306"
       network_mode: bridge
       container_name: mysql-account
       volumes:
         - ${ACCOUNT_MYSQL_DATA:-/opt/data/mysql}:/usr/local/mysql
       hostname: mysql-account
       restart: unless-stopped
    tomcat-account:
       build: tomcat
       ports:
          - "8091:8080"
          - "8001:8000"
       network_mode: bridge
       container_name: tomcat-account
       depends_on:
         - mysql-account
       links:
         - mysql-account
       volumes: 
         - ${ACCOUNT_TOMCAT:-/opt/webapps}:/usr/local/tomcat/webapps
       hostname: tomcat-account
       restart: unless-stopped
